# Generated by Django 2.2.1 on 2019-05-19 08:09

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('floor', models.CharField(max_length=200)),
                ('bible_name', models.CharField(max_length=200)),
                ('main_verses', models.TextField()),
                ('main_verse_start', models.IntegerField()),
                ('main_verse_end', models.IntegerField()),
                ('ref_verse_start', models.IntegerField()),
                ('ref_verse_end', models.IntegerField()),
                ('subject_summary', models.CharField(max_length=500)),
                ('activity_summary', models.CharField(max_length=500)),
                ('note_by_age', models.TextField()),
                ('activity_materials', models.TextField()),
                ('bible_study', models.TextField()),
                ('activity_intro', models.TextField()),
                ('activity_body', models.TextField()),
                ('activity_outro', models.TextField()),
                ('reflection', models.TextField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
