# Generated by Django 2.2.1 on 2019-05-19 09:36

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190519_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='manager',
            field=models.CharField(choices=[('JEA', '조은애 전도사님'), ('BIH', '백인하 전도사님'), ('KSJ', '김성주 전도사님')], default='-', max_length=200, verbose_name='담당 전도사'),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.CharField(default='-', max_length=200, verbose_name='담당 교사'),
        ),
        migrations.AddField(
            model_name='activity',
            name='team',
            field=models.CharField(choices=[('EDUCATION1', '교육 1팀'), ('EDUCATION2', '교육 2팀'), ('COMMUNICATION', '목자팀')], default='EDUCATION1', max_length=200, verbose_name='담당팀'),
        ),
        migrations.AddField(
            model_name='activity',
            name='version',
            field=models.CharField(choices=[('VERSION1', 'Version 1'), ('VERSION2', 'Version 2')], default='VERSION1', max_length=200, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='activity',
            name='year',
            field=models.CharField(default=activities.models.current_year, help_text='활동이 진행된 연도를 입력해주세요. (ex. 2019)', max_length=4),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_body',
            field=models.TextField(verbose_name='활동하기'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_intro',
            field=models.TextField(verbose_name='맞이하기'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_materials',
            field=models.TextField(verbose_name='준비물'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_outro',
            field=models.TextField(verbose_name='보내기'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_summary',
            field=models.CharField(max_length=500, verbose_name='활동 요약'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='bible_name',
            field=models.CharField(choices=[('GENESIS', '창세기'), ('EXODUS', '출애굽기'), ('LEVITICUS', '레위기'), ('NUMBERS', '민수기'), ('DEUTERONOMY', '신명기'), ('JOSHUA', '여호수아'), ('JUDGES', '사사기'), ('RUTH', '룻기'), ('SAMUEL1', '사무엘상'), ('SAMUEL2', '사무엘하'), ('KINGS1', '열왕기상'), ('KINGS2', '열왕기하'), ('CHRONICLES1', '역대상'), ('CHRONICLES2', '역대하'), ('EZRA', '에스라'), ('NEHEMIAH', '느헤미야'), ('ESTHER', '에스더'), ('JOB', '욥기'), ('PSALM', '시편'), ('PROVERBS', '잠언'), ('ECCLESIASTES', '전도서'), ('SONGOFSONGS', '아가'), ('ISAIAH', '이사야'), ('JEREMIAH', '예레미야'), ('LAMENTATIONS', '예레미야애가'), ('EZEKIEL', '에스겔'), ('DANIEL', '다니엘'), ('HOSEA', '호세아'), ('JOEL', '요엘'), ('AMOS', '아모스'), ('OBADIAH', '오바댜'), ('JONAH', '요나'), ('MICAH', '미가'), ('NAHUM', '나훔'), ('HABAKKUK', '하박국'), ('ZEPHANIAH', '스바냐'), ('HAGGAI', '학개'), ('ZECHARIAH', '스가랴'), ('MALACHI', '말라기'), ('MATTHEW', '마태복음'), ('MARK', '마가복음'), ('LUKE', '누가복음'), ('JOHN', '요한복음'), ('ACTS', '사도행전'), ('ROMANS', '로마서'), ('CORINTHIANS1', '고린도전서'), ('CORINTHIANS2', '고린도후서'), ('GALATIANS', '갈라디아서'), ('EPHESIANS', '에베소서'), ('PHILIPPIANS', '빌립보서'), ('COLOSSIANS', '골로새서'), ('THESSALONIANS1', '데살로니가전서'), ('THESSALONIANS2', '데살로니가후서'), ('TIMOTHY1', '디모데전서'), ('TIMOTHY2', '디모데후서'), ('TITUS', '디도서'), ('PHILEMON', '빌레몬서'), ('HEBREWS', '히브리서'), ('JAMES', '야고보서'), ('PETER1', '베드로전서'), ('PETER2', '베드로후서'), ('JOHN1', '요한1서'), ('JOHN2', '요한2서'), ('JOHN3', '요한3서'), ('JUDE', '유다서'), ('REVELATION', '요한계시록')], default='GENESIS', max_length=200, verbose_name='성경'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='bible_study',
            field=models.TextField(verbose_name='본문 해설'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='chapter',
            field=models.IntegerField(verbose_name='마당'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='floor',
            field=models.CharField(choices=[('STORYFLOOR', '하늘마루'), ('MUSICFLOOR', '울림마루'), ('THEATERFLOOR', '연극마루'), ('COOKFLOOR', '만나마루'), ('ARTFLOOR', '그림마루'), ('PLAYFLOOR', '놀이마루')], default='STORYFLOOR', max_length=200, verbose_name='마루'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='main_verse_end',
            field=models.IntegerField(help_text='중심 본문은 몇 장 몇 절 까지 인가요? 예시: 1:1, 10:24', verbose_name='중심 본문 끝절'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='main_verse_start',
            field=models.IntegerField(help_text='중심 본문은 몇 장 몇 절에서 시작하나요? 예시: 1:1, 10:24', verbose_name='중심 본문 시작절'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='main_verses',
            field=models.TextField(verbose_name='중심 본문'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='note_by_age',
            field=models.TextField(verbose_name='연령별 고려사항'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ref_verse_end',
            field=models.IntegerField(help_text='참고 본문은 몇 장 몇 절에서 시작하나요? 예시: 1:1, 10:24', verbose_name='참고 본문 시작절'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ref_verse_start',
            field=models.IntegerField(help_text='참고 본문은 몇 장 몇 절에서 시작하나요? 예시: 1:1, 10:24', verbose_name='참고 본문 시작절'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='reflection',
            field=models.TextField(verbose_name='성찰하기'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject_summary',
            field=models.CharField(max_length=500, verbose_name='한 줄 초점'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=300, verbose_name='활동 제목'),
        ),
    ]
