# Generated by Django 2.2.1 on 2019-05-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20190519_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='manager',
        ),
        migrations.AddField(
            model_name='activity',
            name='pastor',
            field=models.CharField(choices=[('YJY', '윤주열 목사님'), ('JEA', '조은애 전도사님'), ('BIH', '백인하 전도사님'), ('KSJ', '김성주 전도사님')], default='-', max_length=200, verbose_name='담당 교역자'),
        ),
    ]
