# Generated by Django 2.2.1 on 2019-05-26 07:47

from django.db import migrations, models
import notifications.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=300)),
                ('created_date', models.CharField(default=notifications.models.current_date, max_length=100)),
                ('last_update', models.CharField(max_length=100, null=True)),
                ('contents', models.TextField()),
                ('target', models.CharField(choices=[('NOTI1', '전체'), ('NOTI2', '목자팀'), ('NOTI3', '교육1팀'), ('NOTI4', '교육2팀')], default='NOTI1', max_length=100)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
