# Generated by Django 2.2.1 on 2019-05-26 08:00

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_date',
            field=models.DateField(default=notifications.models.current_date),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_update',
            field=models.DateField(default=notifications.models.current_date, null=True),
        ),
    ]
